create contexts for videos and category, add contexts for dynamic page
WildCodeSchool/2022-09-JS-Reims-project-3-origins-digital pull request #36
Opened 2023-01-05 10:23 UTC by DarkOviS

2023-01-06 08:54 UTC, Justine-Merlin requested changes
You made the work of 2 tasks here. You create contexts so it's ok, but you also made a CRUD on category ressource that has no link with the first task (even if you thought so). Make a other branch for category CRUD and remove it from this one.

2023-01-17 16:04 UTC, rocambille commented
conflicts to resolve

2023-01-17 16:31 UTC, rocambille requested changes

2023-01-17 16:31 UTC, rocambille commented on backend/database.sql
> +<<<<<<< HEAD
unresolved conflict

2023-01-19 09:55 UTC, closed without merging