added a fetch for the API
WildCodeSchool/2022-09-JS-Reims-project-3-origins-digital pull request #9
Opened 2022-12-07 14:59 UTC by charlottekieffer

2022-12-07 15:57 UTC, rocambille requested changes

2022-12-07 15:57 UTC, rocambille commented on frontend/src/pages/Home.jsx
> +      `${import.meta.env.VITE_BACKEND_URL ?? "http://localhost:5000"}/movies`
movies or videos: pick one :upside_down_face:

2022-12-07 15:57 UTC, rocambille commented
conflicts to resolve

2022-12-08 08:41 UTC, charlottekieffer commented on frontend/src/pages/Home.jsx
> +      `${import.meta.env.VITE_BACKEND_URL ?? "http://localhost:5000"}/movies`
my bad ! error fixed :)

2022-12-08 09:17 UTC, merged